import type {
  Invite,
  JoinResult,
  QueueItem,
  RoomData,
  RoomState,
  Song,
} from "./types";

// Dev: "/api" is proxied to the Go backend by Vite (see vite.config.ts).
// Prod: set VITE_API_URL to the backend origin once it serves CORS headers.
const API_BASE = import.meta.env.VITE_API_URL ?? "/api";

export class ApiError extends Error {
  constructor(
    public status: number,
    message: string,
  ) {
    super(message);
    this.name = "ApiError";
  }
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  let res: Response;
  try {
    res = await fetch(`${API_BASE}${path}`, {
      ...init,
      headers: { "Content-Type": "application/json", ...init?.headers },
    });
  } catch {
    throw new ApiError(0, "Can't reach the server. Is the backend running?");
  }

  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new ApiError(res.status, text || `Request failed (${res.status})`);
  }

  if (res.status === 204) return undefined as T;
  const body = await res.text();
  return (body ? JSON.parse(body) : undefined) as T;
}

export const api = {
  health: () => request<{ status: string }>("/health"),

  createRoom: (hostID: string) =>
    request<RoomData>("/rooms", {
      method: "POST",
      body: JSON.stringify({ hostID }),
    }),

  getRoom: (roomID: string) => request<RoomData>(`/rooms/${roomID}`),

  // Join straight from a room code. Pass an existing userID to keep the same
  // identity (and votes) across a refresh; omit it to be assigned a new one.
  // Also the cheapest way to check a code is real before opening a socket.
  joinRoom: (roomID: string, userID?: string) =>
    request<JoinResult>(`/rooms/${roomID}/join`, {
      method: "POST",
      body: JSON.stringify({ userID: userID ?? "" }),
    }),

  // Invite tokens predate room codes and are no longer generated by the UI.
  // These stay so links handed out earlier keep working.
  createInvite: (roomID: string, maxUses = 5, validHours = 24) =>
    request<Invite>(`/rooms/${roomID}/invites`, {
      method: "POST",
      body: JSON.stringify({ maxUses, validHours }),
    }),

  joinInvite: (token: string) =>
    request<JoinResult>(`/invites/${token}/join`, { method: "POST" }),

  getQueue: (roomID: string) => request<QueueItem[]>(`/rooms/${roomID}/queue`),

  addSong: (roomID: string, song: Song) =>
    request<QueueItem[]>(`/rooms/${roomID}/queue`, {
      method: "POST",
      body: JSON.stringify(song),
    }),

  // Toggles this user's vote (one per user per song).
  voteSong: (roomID: string, songID: string, userID: string) =>
    request<QueueItem[]>(
      `/rooms/${roomID}/queue/${songID}/vote?userID=${encodeURIComponent(userID)}`,
      { method: "POST" },
    ),

  deleteSong: (roomID: string, songID: string, userID: string) =>
    request<QueueItem[]>(
      `/rooms/${roomID}/queue/${songID}?userID=${encodeURIComponent(userID)}`,
      { method: "DELETE" },
    ),

  // Advances the queue and returns the new RoomState. userID is checked against
  // the host when playback is host-only.
  //
  // afterSongID names the song the caller believes is playing. Pass it for
  // automatic end-of-song advances: the backend then only advances if that song
  // is still current, so every client in the room can fire this at once and the
  // queue still moves exactly one step. It also lets a listener advance past a
  // genuinely finished track in a host-only room, so a room whose host closed
  // their tab doesn't sit on a dead song forever.
  advanceQueue: (roomID: string, userID: string, afterSongID?: string) =>
    request<RoomState>(`/rooms/${roomID}/queue/next`, {
      method: "POST",
      body: JSON.stringify({ userID, afterSongID: afterSongID ?? "" }),
    }),

  // Search YouTube in-app (keyless InnerTube, backed by the Go /search route).
  search: (query: string, limit = 15) =>
    request<Song[]>(
      `/search?q=${encodeURIComponent(query)}&limit=${limit}`,
    ),

  // Resolve a YouTube playlist URL to its songs (preview, no mutation).
  resolvePlaylist: (url: string) =>
    request<{ songs: Song[] }>(`/playlist?url=${encodeURIComponent(url)}`),

  // Append many songs to the queue in one write (used by playlist import).
  addBatch: (roomID: string, songs: Song[]) =>
    request<QueueItem[]>(`/rooms/${roomID}/queue/batch`, {
      method: "POST",
      body: JSON.stringify({ songs }),
    }),

  // Set the room's current song directly ("Play now").
  playNow: (roomID: string, song: Song, userID: string) =>
    request<RoomState>(`/rooms/${roomID}/play`, {
      method: "POST",
      body: JSON.stringify({ song, userID }),
    }),

  // Host-only: hand playback control to everyone, or take it back.
  setControl: (roomID: string, userID: string, everyoneControls: boolean) =>
    request<RoomState>(`/rooms/${roomID}/control`, {
      method: "POST",
      body: JSON.stringify({ userID, everyoneControls }),
    }),
};
